//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_User
    {
        public Nullable<int> Deprtment_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public int Department_User_Id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
