//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Document_Parameter
    {
        public int Object_Document_Parameter1 { get; set; }
        public Nullable<int> Object_Document_Id { get; set; }
        public Nullable<int> Parameter_Id { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Object_Document Object_Document { get; set; }
        public virtual Parameter Parameter { get; set; }
    }
}
