//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_Document()
        {
            this.Object_Document_Parameter = new HashSet<Object_Document_Parameter>();
        }
    
        public int Object_Document_Id { get; set; }
        public Nullable<int> Object_Id { get; set; }
        public Nullable<int> Document_Specialty_Id { get; set; }
    
        public virtual Document_Specialty Document_Specialty { get; set; }
        public virtual Object Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Document_Parameter> Object_Document_Parameter { get; set; }
    }
}
