//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Speciality
    {
        public int Object_Speciality_Id { get; set; }
        public Nullable<int> Object_Document_Id { get; set; }
        public Nullable<int> Speciality_Id { get; set; }
    
        public virtual Object_Document Object_Document { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
