//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Object
    {
        public Nullable<int> In_Object_Id { get; set; }
        public Nullable<int> Out_Object_Id { get; set; }
        public int Object_Object_Id { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual Object Object1 { get; set; }
    }
}
