//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter_Parameter
    {
        public int Parameter_Parameter_Id { get; set; }
        public Nullable<int> Parameter_First { get; set; }
        public Nullable<int> Parameter_Second { get; set; }
    
        public virtual Parameter Parameter { get; set; }
        public virtual Parameter Parameter1 { get; set; }
    }
}
