//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZepProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variation_Object
    {
        public int Variation_Object_Id { get; set; }
        public Nullable<int> Object_Id { get; set; }
        public Nullable<int> Variation_Id { get; set; }
    
        public virtual Object_Library Object_Library { get; set; }
        public virtual Variation Variation { get; set; }
    }
}
