USE [master]
GO

/****** Object:  Database [ObjectZEP]    Script Date: 28.04.2017 0:18:18 ******/
DROP DATABASE [ObjectZEP]
GO

/****** Object:  Database [ObjectZEP]    Script Date: 28.04.2017 0:18:18 ******/
CREATE DATABASE [ObjectZEP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ObjectZEP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ObjectZEP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ObjectZEP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ObjectZEP_log.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ObjectZEP] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ObjectZEP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ObjectZEP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ObjectZEP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ObjectZEP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ObjectZEP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ObjectZEP] SET ARITHABORT OFF 
GO

ALTER DATABASE [ObjectZEP] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ObjectZEP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ObjectZEP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ObjectZEP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ObjectZEP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ObjectZEP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ObjectZEP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ObjectZEP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ObjectZEP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ObjectZEP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ObjectZEP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ObjectZEP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ObjectZEP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ObjectZEP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ObjectZEP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ObjectZEP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ObjectZEP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ObjectZEP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ObjectZEP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ObjectZEP] SET  MULTI_USER 
GO

ALTER DATABASE [ObjectZEP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ObjectZEP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ObjectZEP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ObjectZEP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ObjectZEP] SET  READ_WRITE 
GO

