//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public string Задача { get; set; }
        public string Классификатор_задачи { get; set; }
        public string Объект { get; set; }
        public string Классификатор_объекта { get; set; }
        public string Модель { get; set; }
        public string Классификатор_модели { get; set; }
    }
}
