//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Object_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model_Object_Task()
        {
            this.Predecessor = new HashSet<Predecessor>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Object { get; set; }
        public Nullable<int> Task { get; set; }
        public Nullable<int> Model { get; set; }
        public string Project_Stage { get; set; }
    
        public virtual Model_Classified Model_Classified { get; set; }
        public virtual Object_Classified Object_Classified { get; set; }
        public virtual Task_Classified Task_Classified { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predecessor> Predecessor { get; set; }
    }
}
