//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Classified
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_Classified()
        {
            this.Model_Object_Task = new HashSet<Model_Object_Task>();
        }
    
        public int ID { get; set; }
        public int Object { get; set; }
        public Nullable<int> Object_Code_1 { get; set; }
        public Nullable<int> Object_Code_2 { get; set; }
        public Nullable<int> Location { get; set; }
    
        public virtual Location_Classified Location_Classified { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Model_Object_Task> Model_Object_Task { get; set; }
        public virtual Object Object1 { get; set; }
        public virtual Object_Classificator Object_Classificator { get; set; }
        public virtual Object_Classificator_2 Object_Classificator_2 { get; set; }
    }
}
