//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Object_Classified = new HashSet<Object_Classified>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> HierLevel { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> FunctionID { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Location Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Classified> Object_Classified { get; set; }
    }
}
