//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Person_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
