//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predecessor
    {
        public int ID { get; set; }
        public int Task { get; set; }
        public int Task_Pred { get; set; }
    
        public virtual Model_Object_Task Model_Object_Task { get; set; }
    }
}
