//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Classificator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_Classificator()
        {
            this.Task_Classified = new HashSet<Task_Classified>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string TaskGroup { get; set; }
        public string Group_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Classified> Task_Classified { get; set; }
    }
}
